<?php
/**
 * Child Theme Generator Class
 * 
 * @package WP_Child_Theme_Pro
 * @since 1.0.0
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

class WP_Child_Theme_Generator {

    /**
     * Constructor
     */
    public function __construct() {
        // Initialize
    }

    /**
     * Generate a child theme
     *
     * @param string|array $parent_theme Parent theme slug or array of params
     * @param string $child_name Child theme name
     * @param string $child_desc Child theme description
     * @param string $child_author Child theme author
     * @param string $child_version Child theme version
     * @param bool $copy_settings Whether to copy parent theme settings
     * @param array $selected_files Files to copy from parent theme
     * @return string|WP_Error Child theme slug or error
     */
    public function generate_child_theme($parent_theme, $child_name = '', $child_desc = '', $child_author = '', $child_version = '1.0.0', $copy_settings = false, $selected_files = array()) {
        // Handle array input (from AJAX call)
        if (is_array($parent_theme)) {
            $args = $parent_theme;
            $parent_theme = isset($args['parent_theme']) ? $args['parent_theme'] : '';
            $child_name = isset($args['child_name']) ? $args['child_name'] : '';
            $child_desc = isset($args['child_desc']) ? $args['child_desc'] : '';
            $child_author = isset($args['child_author']) ? $args['child_author'] : '';
            $child_version = isset($args['child_version']) ? $args['child_version'] : '1.0.0';
            $copy_settings = isset($args['copy_settings']) ? (bool) $args['copy_settings'] : false;
            $selected_files = isset($args['selected_files']) ? $args['selected_files'] : array();
        }
        
        // Validate parent theme
        $themes = wp_get_themes();
        if (!isset($themes[$parent_theme])) {
            return new WP_Error('invalid_parent', __('Invalid parent theme.', 'wp-child-theme-pro'));
        }
        
        // Get parent theme data
        $parent = $themes[$parent_theme];
        
        // Create child theme slug
        $child_slug = sanitize_title($child_name);
        
        // Check if child theme already exists
        if (isset($themes[$child_slug])) {
            return new WP_Error('theme_exists', __('A theme with this name already exists.', 'wp-child-theme-pro'));
        }
        
        // Set child theme directory
        $themes_dir = get_theme_root();
        $child_dir = trailingslashit($themes_dir) . $child_slug;
        $parent_dir = trailingslashit($themes_dir) . $parent_theme;
        
        // Use WordPress filesystem API
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        // Create child theme directory
        if (!$wp_filesystem->mkdir($child_dir)) {
            error_log('WP Child Theme Pro: Failed to create directory at ' . $child_dir);
            return new WP_Error('mkdir_failed', __('Failed to create child theme directory.', 'wp-child-theme-pro'));
        }
        
        // Create style.css with proper content
        $css_content = "/*\n";
        $css_content .= "Theme Name: " . $child_name . "\n";
        $css_content .= "Theme URI: \n";
        $css_content .= "Description: " . $child_desc . "\n";
        $css_content .= "Author: " . $child_author . "\n";
        $css_content .= "Author URI: \n";
        $css_content .= "Template: " . $parent_theme . "\n";
        $css_content .= "Version: " . $child_version . "\n";
        $css_content .= "License: GNU General Public License v2 or later\n";
        $css_content .= "License URI: http://www.gnu.org/licenses/gpl-2.0.html\n";
        $css_content .= "Text Domain: " . $child_slug . "\n";
        $css_content .= "*/\n\n";
        $css_content .= "/* =Theme customization starts here\n";
        $css_content .= "------------------------------------------------------------ */\n";
        
        $style_css = trailingslashit($child_dir) . 'style.css';
        if (!$wp_filesystem->put_contents($style_css, $css_content, FS_CHMOD_FILE)) {
            error_log('WP Child Theme Pro: Failed to write to file ' . $style_css);
            // Clean up
            $this->delete_theme($child_slug);
            return new WP_Error('css_failed', __('Failed to create style.css.', 'wp-child-theme-pro'));
        }
        
        // Create a basic functions.php for all themes
        $functions_content = "<?php\n";
        $functions_content .= "/**\n";
        $functions_content .= " * " . $child_name . " functions and definitions\n";
        $functions_content .= " * Generated by WP Child Theme Pro\n";
        $functions_content .= " * \n";
        $functions_content .= " * @package " . str_replace(' ', '_', $child_name) . "\n";
        $functions_content .= " */\n\n";
        
        // Add code to enqueue parent theme styles
        $functions_content .= "/**\n";
        $functions_content .= " * Enqueue parent theme styles and child theme CSS\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_enqueue_styles() {\n";
        $functions_content .= "    // Enqueue parent style\n";
        $functions_content .= "    wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');\n";
        $functions_content .= "    // Enqueue child style\n";
        $functions_content .= "    wp_enqueue_style('child-style',\n";
        $functions_content .= "        get_stylesheet_directory_uri() . '/style.css',\n";
        $functions_content .= "        array('parent-style'),\n";
        $functions_content .= "        wp_get_theme()->get('Version')\n";
        $functions_content .= "    );\n";
        $functions_content .= "    // Enqueue custom CSS if option enabled\n";
        $functions_content .= "    wp_enqueue_style('mytheme-custom-css',\n";
        $functions_content .= "        get_stylesheet_directory_uri() . '/assets/css/mytheme.css',\n";
        $functions_content .= "        array('child-style'),\n";
        $functions_content .= "        wp_get_theme()->get('Version')\n";
        $functions_content .= "    );\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_enqueue_scripts', '" . str_replace('-', '_', $child_slug) . "_enqueue_styles');\n\n";
        
        // Add JS enqueue function
        $functions_content .= "/**\n";
        $functions_content .= " * Enqueue child theme scripts\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_enqueue_scripts() {\n";
        $functions_content .= "    // Enqueue custom JS\n";
        $functions_content .= "    wp_enqueue_script('mytheme-custom-script',\n";
        $functions_content .= "        get_stylesheet_directory_uri() . '/assets/js/mytheme.js',\n";
        $functions_content .= "        array('jquery'),\n";
        $functions_content .= "        wp_get_theme()->get('Version'),\n";
        $functions_content .= "        true\n";
        $functions_content .= "    );\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_enqueue_scripts', '" . str_replace('-', '_', $child_slug) . "_enqueue_scripts');\n\n";
        
        // Add custom CSS to head
        $functions_content .= "/**\n";
        $functions_content .= " * Add custom CSS to head\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_custom_css() {\n";
        $functions_content .= "    // Get custom CSS option from theme mods\n";
        $functions_content .= "    \$custom_css = get_theme_mod('" . $child_slug . "_custom_css', '');\n";
        $functions_content .= "    if (!empty(\$custom_css)) {\n";
        $functions_content .= "        echo '<style type=\"text/css\">' . wp_strip_all_tags(\$custom_css) . '</style>';\n";
        $functions_content .= "    }\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_head', '" . str_replace('-', '_', $child_slug) . "_custom_css', 100);\n\n";
        
        // Add custom JS to footer
        $functions_content .= "/**\n";
        $functions_content .= " * Add custom JS to footer\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_custom_js() {\n";
        $functions_content .= "    // Get custom JS option from theme mods\n";
        $functions_content .= "    \$custom_js = get_theme_mod('" . $child_slug . "_custom_js', '');\n";
        $functions_content .= "    if (!empty(\$custom_js)) {\n";
        $functions_content .= "        echo '<script type=\"text/javascript\">' . \$custom_js . '</script>';\n";
        $functions_content .= "    }\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_footer', '" . str_replace('-', '_', $child_slug) . "_custom_js', 100);\n\n";
        
        // Add customizer options for custom CSS and JS
        $functions_content .= "/**\n";
        $functions_content .= " * Add customizer options for custom CSS and JS\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_customizer_options(\$wp_customize) {\n";
        $functions_content .= "    // Add section for custom code\n";
        $functions_content .= "    \$wp_customize->add_section('" . $child_slug . "_custom_code', array(\n";
        $functions_content .= "        'title'    => __('Custom CSS & JS', '" . $child_slug . "'),\n";
        $functions_content .= "        'priority' => 200,\n";
        $functions_content .= "    ));\n\n";
        
        $functions_content .= "    // Add custom CSS setting\n";
        $functions_content .= "    \$wp_customize->add_setting('" . $child_slug . "_custom_css', array(\n";
        $functions_content .= "        'default'           => '',\n";
        $functions_content .= "        'sanitize_callback' => 'wp_strip_all_tags',\n";
        $functions_content .= "        'type'              => 'theme_mod',\n";
        $functions_content .= "    ));\n\n";
        
        $functions_content .= "    // Add custom CSS control\n";
        $functions_content .= "    \$wp_customize->add_control('" . $child_slug . "_custom_css', array(\n";
        $functions_content .= "        'label'       => __('Custom CSS', '" . $child_slug . "'),\n";
        $functions_content .= "        'description' => __('Add custom CSS here. Do not include style tags.', '" . $child_slug . "'),\n";
        $functions_content .= "        'section'     => '" . $child_slug . "_custom_code',\n";
        $functions_content .= "        'type'        => 'textarea',\n";
        $functions_content .= "    ));\n\n";
        
        $functions_content .= "    // Add custom JS setting\n";
        $functions_content .= "    \$wp_customize->add_setting('" . $child_slug . "_custom_js', array(\n";
        $functions_content .= "        'default'           => '',\n";
        $functions_content .= "        'type'              => 'theme_mod',\n";
        $functions_content .= "    ));\n\n";
        
        $functions_content .= "    // Add custom JS control\n";
        $functions_content .= "    \$wp_customize->add_control('" . $child_slug . "_custom_js', array(\n";
        $functions_content .= "        'label'       => __('Custom JavaScript', '" . $child_slug . "'),\n";
        $functions_content .= "        'description' => __('Add custom JavaScript here. Do not include script tags.', '" . $child_slug . "'),\n";
        $functions_content .= "        'section'     => '" . $child_slug . "_custom_code',\n";
        $functions_content .= "        'type'        => 'textarea',\n";
        $functions_content .= "    ));\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('customize_register', '" . str_replace('-', '_', $child_slug) . "_customizer_options');\n\n";
        
        // Add any custom child theme functionality here
        $functions_content .= "// Add any custom functions below this line\n\n";
        
        $functions_php = trailingslashit($child_dir) . 'functions.php';
        if (!$wp_filesystem->put_contents($functions_php, $functions_content, FS_CHMOD_FILE)) {
            error_log('WP Child Theme Pro: Failed to write to file ' . $functions_php);
            // Clean up
            $this->delete_theme($child_slug);
            return new WP_Error('functions_failed', __('Failed to create functions.php.', 'wp-child-theme-pro'));
        }
        
        // Create screenshot.png
        $this->create_screenshot($parent_theme, $child_dir);
        
        // Create assets directory structure
        $assets_dir = trailingslashit($child_dir) . 'assets';
        $js_dir = trailingslashit($assets_dir) . 'js';
        $css_dir = trailingslashit($assets_dir) . 'css';
        
        if (!$wp_filesystem->mkdir($assets_dir)) {
            error_log('WP Child Theme Pro: Failed to create assets directory');
        }
        
        if (!$wp_filesystem->mkdir($js_dir)) {
            error_log('WP Child Theme Pro: Failed to create js directory');
        } else {
            // Create mytheme.js
            $js_content = "/**\n";
            $js_content .= " * Custom JS for " . $child_name . "\n";
            $js_content .= " * Generated by WP Child Theme Pro\n";
            $js_content .= " */\n\n";
            $js_content .= "jQuery(document).ready(function($) {\n";
            $js_content .= "    // Add your custom JavaScript code here\n";
            $js_content .= "    console.log('Child theme custom JS loaded');\n";
            $js_content .= "});\n";
            
            $mytheme_js = trailingslashit($js_dir) . 'mytheme.js';
            $wp_filesystem->put_contents($mytheme_js, $js_content, FS_CHMOD_FILE);
        }
        
        if (!$wp_filesystem->mkdir($css_dir)) {
            error_log('WP Child Theme Pro: Failed to create css directory');
        } else {
            // Create mytheme.css
            $mytheme_css_content = "/**\n";
            $mytheme_css_content .= " * Custom CSS for " . $child_name . "\n";
            $mytheme_css_content .= " * Generated by WP Child Theme Pro\n";
            $mytheme_css_content .= " */\n\n";
            $mytheme_css_content .= "/* Add your custom CSS rules here */\n";
            
            $mytheme_css = trailingslashit($css_dir) . 'mytheme.css';
            $wp_filesystem->put_contents($mytheme_css, $mytheme_css_content, FS_CHMOD_FILE);
        }
        
        // Copy parent theme settings if enabled
        if ($copy_settings) {
            $this->copy_parent_settings($parent_theme, $child_slug);
        }
        
        // Activate child theme
        $this->activate_child_theme($child_slug);
        
        return $child_slug;
    }

    /**
     * Activate child theme
     * 
     * @param string $child_slug Child theme slug
     * @return bool Whether activation was successful
     */
    public function activate_child_theme($child_slug = '') {
        // Use instance property if no slug provided
        if (empty($child_slug) && !empty($this->child_theme_slug)) {
            $child_slug = $this->child_theme_slug;
        }
        
        if ($child_slug) {
            switch_theme($child_slug);
            
            // Add a transient to show an admin notice
            set_transient('wpchild_theme_activated', $child_slug, 5);
            
            return true;
        }
        
        return false;
    }

    /**
     * Add admin notices
     */
    public function admin_notices() {
        // Check for theme activated notice
        $activated_theme = get_transient('wpchild_theme_activated');
        
        if ($activated_theme) {
            // Clear the transient
            delete_transient('wpchild_theme_activated');
            
            $theme = wp_get_theme($activated_theme);
            $theme_name = $theme->get('Name');
            
            ?>
            <div class="notice notice-success is-dismissible">
                <p><?php 
                // translators: %s - describe the placeholder (e.g. the generated theme name)
                printf(esc_html__('Child theme "%s" has been created and activated successfully!', 'wp-child-theme-pro'), $theme_name); ?></p>
            </div>
            <?php
        }
    }

    /**
     * Copy a file from parent theme to child theme
     *
     * @param string $parent_dir Parent theme directory
     * @param string $child_dir Child theme directory
     * @param string $file File path relative to theme root
     */
    private function copy_parent_file($parent_dir, $child_dir, $file) {
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem if not already done
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        $file = sanitize_file_name($file);
        $source = trailingslashit($parent_dir) . $file;
        $destination = trailingslashit($child_dir) . $file;
        
        // Skip if source doesn't exist
        if (!$wp_filesystem->exists($source)) {
            return;
        }
        
        // Create directory if needed
        $destination_dir = dirname($destination);
        if (!$wp_filesystem->is_dir($destination_dir)) {
            $wp_filesystem->mkdir($destination_dir, FS_CHMOD_DIR);
        }
        
        // Copy file
        $wp_filesystem->copy($source, $destination, true, FS_CHMOD_FILE);
    }

    /**
     * Copy parent theme settings to child theme
     *
     * @param string $parent_theme Parent theme slug
     * @param string $child_theme Child theme slug
     */
    private function copy_parent_settings($parent_theme, $child_theme) {
        // Get all theme mods for parent theme
        $parent_mods = get_option('theme_mods_' . $parent_theme);
        
        if ($parent_mods) {
            // Set theme mods for child theme
            update_option('theme_mods_' . $child_theme, $parent_mods);
        }
    }

    /**
     * Create screenshot for child theme
     *
     * @param string $parent_theme Parent theme slug
     * @param string $child_dir Child theme directory
     */
    private function create_screenshot($parent_theme, $child_dir) {
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem if not already done
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        // Check if parent theme has screenshot
        $parent_screenshot = get_theme_root() . '/' . $parent_theme . '/screenshot.png';
        
        if ($wp_filesystem->exists($parent_screenshot)) {
            // Copy parent screenshot
            $wp_filesystem->copy($parent_screenshot, trailingslashit($child_dir) . 'screenshot.png', true, FS_CHMOD_FILE);
        } else {
            // Create default screenshot
            $this->create_default_screenshot($child_dir);
        }
    }

    /**
     * Create default screenshot
     *
     * @param string $child_dir Child theme directory
     */
    private function create_default_screenshot($child_dir) {
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem if not already done
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        // Use default screenshot from plugin
        $default_screenshot = WPCHILD_PLUGIN_DIR . 'admin/images/default-screenshot.png';
        
        if ($wp_filesystem->exists($default_screenshot)) {
            $wp_filesystem->copy($default_screenshot, trailingslashit($child_dir) . 'screenshot.png', true, FS_CHMOD_FILE);
        } else {
            // Create a blank screenshot if default doesn't exist
            $this->create_blank_screenshot($child_dir);
        }
    }
    
    /**
     * Create a blank screenshot
     *
     * @param string $child_dir Child theme directory
     */
    private function create_blank_screenshot($child_dir) {
        // Only attempt if GD is available
        if (function_exists('imagecreatetruecolor')) {
            $img = imagecreatetruecolor(1200, 900);
            $bg_color = imagecolorallocate($img, 240, 240, 240);
            $text_color = imagecolorallocate($img, 50, 50, 50);
            
            imagefill($img, 0, 0, $bg_color);
            
            // Add text
            $text = 'WP Child Theme Pro';
            if (function_exists('imagettftext') && file_exists(WPCHILD_PLUGIN_DIR . 'admin/fonts/OpenSans-Regular.ttf')) {
                imagettftext($img, 40, 0, 100, 400, $text_color, WPCHILD_PLUGIN_DIR . 'admin/fonts/OpenSans-Regular.ttf', $text);
            } else {
                imagestring($img, 5, 100, 400, $text, $text_color);
            }
            
            // Save the image
            imagepng($img, trailingslashit($child_dir) . 'screenshot.png');
            imagedestroy($img);
        }
    }

    /**
     * Delete a theme
     *
     * @param string $theme_slug Theme slug
     */
    private function delete_theme($theme_slug) {
        $theme_dir = get_theme_root() . '/' . $theme_slug;
        $this->recursive_delete($theme_dir);
    }

    /**
     * Recursively delete a directory
     *
     * @param string $dir Directory path
     */
    private function recursive_delete($dir) {
        if (!is_dir($dir)) {
            return;
        }
        
        $files = array_diff(scandir($dir), array('.', '..'));
        
        foreach ($files as $file) {
            if (is_dir("$dir/$file")) {
                $this->recursive_delete("$dir/$file");
            } else {
                unlink("$dir/$file");
            }
        }
        
        rmdir($dir);
    }

    /**
     * Get list of files from parent theme
     *
     * @param string $parent_theme Parent theme slug
     * @return array File list
     */
    public function get_parent_theme_files($parent_theme) {
        $parent_dir = get_theme_root() . '/' . $parent_theme;
        
        if (!is_dir($parent_dir)) {
            return array();
        }
        
        return $this->scan_directory($parent_dir, '', array());
    }

    /**
     * Scan directory recursively
     *
     * @param string $base Base directory
     * @param string $dir Current directory
     * @param array $results Results array
     * @return array File list
     */
    private function scan_directory($base, $dir, $results) {
        $files = scandir($base . '/' . $dir);
        
        foreach ($files as $file) {
            if ($file == '.' || $file == '..') {
                continue;
            }
            
            $path = $dir . ($dir ? '/' : '') . $file;
            $full_path = $base . '/' . $path;
            
            if (is_dir($full_path)) {
                $results = $this->scan_directory($base, $path, $results);
            } else {
                $results[] = $path;
            }
        }
        
        return $results;
    }

    /**
     * Check if parent theme has includes directory with specific structure
     *
     * @param string $parent_dir Parent theme directory
     * @return bool Whether the parent theme has the includes directory with specific structure
     */
    private function check_for_includes_structure($parent_dir) {
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem if not already done
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        // Check if parent theme has includes directory with admin-functions.php file
        if ($wp_filesystem->exists($parent_dir . '/includes/admin-functions.php')) {
            return true;
        }
        
        return false;
    }

    /**
     * Copy includes directory from parent theme to child theme
     *
     * @param string $parent_dir Parent theme directory
     * @param string $child_dir Child theme directory
     */
    private function copy_includes_directory($parent_dir, $child_dir) {
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem if not already done
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        // Create includes directory
        $wp_filesystem->mkdir($child_dir . '/includes');
        
        // Copy important include files
        $important_includes = [
            '/includes/admin-functions.php',
            '/includes/settings-functions.php',
            '/includes/elementor-functions.php',
            '/includes/customizer-functions.php'
        ];
        
        foreach ($important_includes as $include_file) {
            if ($wp_filesystem->exists($parent_dir . $include_file)) {
                $wp_filesystem->copy($parent_dir . $include_file, $child_dir . $include_file, true, FS_CHMOD_FILE);
            }
        }
    }

    /**
     * For Hello Elementor theme, create a special functions.php
     * 
     * @param string $parent_dir Parent theme directory
     * @param string $child_dir Child theme directory
     * @param string $child_slug Child theme slug
     * @return bool Whether the file was created successfully
     */
    private function create_hello_elementor_functions($parent_dir, $child_dir, $child_slug) {
        global $wp_filesystem;
        
        // Initialize the WordPress filesystem if not already done
        if (empty($wp_filesystem)) {
            require_once(ABSPATH . '/wp-admin/includes/file.php');
            WP_Filesystem();
        }
        
        // Create includes directory
        $includes_dir = trailingslashit($child_dir) . 'includes';
        $wp_filesystem->mkdir($includes_dir);
        
        // Copy important include files from parent theme
        $include_files = array(
            'admin-functions.php',
            'settings-functions.php',
            'elementor-functions.php',
            'customizer-functions.php'
        );
        
        foreach ($include_files as $include_file) {
            $source = trailingslashit($parent_dir) . 'includes/' . $include_file;
            $destination = trailingslashit($includes_dir) . $include_file;
            
            if ($wp_filesystem->exists($source)) {
                $wp_filesystem->copy($source, $destination, true, FS_CHMOD_FILE);
            }
        }
        
        // Add special handling for Hello Elementor functions
        $functions_content = "<?php\n";
        $functions_content .= "/**\n";
        $functions_content .= " * Theme functions and definitions\n";
        $functions_content .= " *\n";
        $functions_content .= " * @package Hello Elementor Child\n";
        $functions_content .= " */\n\n";
        
        $functions_content .= "// Exit if accessed directly\n";
        $functions_content .= "if ( ! defined( 'ABSPATH' ) ) {\n";
        $functions_content .= "\texit; // Exit if accessed directly.\n";
        $functions_content .= "}\n\n";
        
        // Define content width
        $functions_content .= "if ( ! isset( \$content_width ) ) {\n";
        $functions_content .= "\t\$content_width = 800; // Pixels.\n";
        $functions_content .= "}\n\n";
        
        // Define theme version (from parent)
        $functions_content .= "define( 'HELLO_ELEMENTOR_VERSION', '3.1.1' );\n\n";
        
        // Enqueue styles
        $functions_content .= "/**\n";
        $functions_content .= " * Enqueue parent theme styles and child theme CSS\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_enqueue_styles() {\n";
        $functions_content .= "\t// Enqueue parent style\n";
        $functions_content .= "\twp_enqueue_style('hello-elementor', get_template_directory_uri() . '/style.min.css');\n";
        $functions_content .= "\twp_enqueue_style('hello-elementor-theme-style', get_template_directory_uri() . '/theme.min.css');\n";
        $functions_content .= "\t// Enqueue child style\n";
        $functions_content .= "\twp_enqueue_style('hello-elementor-child', get_stylesheet_directory_uri() . '/style.css', array('hello-elementor'), wp_get_theme()->get('Version'));\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_enqueue_scripts', '" . str_replace('-', '_', $child_slug) . "_enqueue_styles', 20);\n\n";
        
        // Add custom JS enqueue
        $functions_content .= "/**\n";
        $functions_content .= " * Enqueue child theme scripts\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_enqueue_scripts() {\n";
        $functions_content .= "\t// Enqueue custom JS if it exists\n";
        $functions_content .= "\tif (file_exists(get_stylesheet_directory() . '/js/custom.js')) {\n";
        $functions_content .= "\t\twp_enqueue_script('child-custom-script',\n";
        $functions_content .= "\t\t\tget_stylesheet_directory_uri() . '/js/custom.js',\n";
        $functions_content .= "\t\t\tarray('jquery'),\n";
        $functions_content .= "\t\t\twp_get_theme()->get('Version'),\n";
        $functions_content .= "\t\t\ttrue\n";
        $functions_content .= "\t\t);\n";
        $functions_content .= "\t}\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_enqueue_scripts', '" . str_replace('-', '_', $child_slug) . "_enqueue_scripts');\n\n";
        
        // Include admin functions
        $functions_content .= "// Admin notice\n";
        $functions_content .= "if ( is_admin() ) {\n";
        $functions_content .= "\trequire get_stylesheet_directory() . '/includes/admin-functions.php';\n";
        $functions_content .= "}\n\n";
        
        // Include other important files
        $functions_content .= "// Settings page\n";
        $functions_content .= "require get_stylesheet_directory() . '/includes/settings-functions.php';\n\n";
        
        $functions_content .= "// Header & footer styling option, inside Elementor\n";
        $functions_content .= "require get_stylesheet_directory() . '/includes/elementor-functions.php';\n\n";
        
        // Customizer functions
        $functions_content .= "if ( ! function_exists( 'hello_elementor_customizer' ) ) {\n";
        $functions_content .= "\t// Customizer controls\n";
        $functions_content .= "\tfunction hello_elementor_customizer() {\n";
        $functions_content .= "\t\tif ( ! is_customize_preview() ) {\n";
        $functions_content .= "\t\t\treturn;\n";
        $functions_content .= "\t\t}\n\n";
        $functions_content .= "\t\tif ( ! hello_elementor_display_header_footer() ) {\n";
        $functions_content .= "\t\t\treturn;\n";
        $functions_content .= "\t\t}\n\n";
        $functions_content .= "\t\trequire get_stylesheet_directory() . '/includes/customizer-functions.php';\n";
        $functions_content .= "\t}\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action( 'init', 'hello_elementor_customizer' );\n\n";
        
        // Add any custom functions below this line
        $functions_content .= "// Add your custom functions below this line\n";
        
        $functions_php = trailingslashit($child_dir) . 'functions.php';
        return $wp_filesystem->put_contents($functions_php, $functions_content, FS_CHMOD_FILE);
    }
}
