<?php
/**
 * Child Theme Generator Class
 * 
 * @package WP_Child_Theme_Pro
 * @since 1.0.0
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

class WP_Child_Theme_Generator {

    /**
     * Constructor
     */
    public function __construct() {
        // Initialize
    }

    /**
     * Generate a child theme
     *
     * @param string $parent_theme Parent theme slug
     * @param string $child_name Child theme name
     * @param string $child_desc Child theme description
     * @param string $child_author Child theme author
     * @param string $child_version Child theme version
     * @param bool $copy_settings Whether to copy parent theme settings
     * @param array $selected_files Files to copy from parent theme
     * @return string|WP_Error Child theme slug or error
     */
    public function generate_child_theme($parent_theme, $child_name, $child_desc = '', $child_author = '', $child_version = '1.0.0', $copy_settings = false, $selected_files = array()) {
        // Validate parent theme
        $themes = wp_get_themes();
        if (!isset($themes[$parent_theme])) {
            return new WP_Error('invalid_parent', __('Invalid parent theme.', 'wp-child-theme-pro'));
        }
        
        // Get parent theme data
        $parent = $themes[$parent_theme];
        
        // Create child theme slug
        $child_slug = sanitize_title($child_name);
        
        // Check if child theme already exists
        if (isset($themes[$child_slug])) {
            return new WP_Error('theme_exists', __('A theme with this name already exists.', 'wp-child-theme-pro'));
        }
        
        // Set child theme directory
        $themes_dir = get_theme_root();
        $child_dir = trailingslashit($themes_dir) . $child_slug;
        
        // Create child theme directory
        if (!wp_mkdir_p($child_dir)) {
            return new WP_Error('mkdir_failed', __('Failed to create child theme directory.', 'wp-child-theme-pro'));
        }
        
        // Create style.css
        $css_content = "/*\n";
        $css_content .= "Theme Name: " . $child_name . "\n";
        $css_content .= "Theme URI: \n";
        $css_content .= "Description: " . $child_desc . "\n";
        $css_content .= "Author: " . $child_author . "\n";
        $css_content .= "Author URI: \n";
        $css_content .= "Template: " . $parent_theme . "\n";
        $css_content .= "Version: " . $child_version . "\n";
        $css_content .= "License: GNU General Public License v2 or later\n";
        $css_content .= "License URI: http://www.gnu.org/licenses/gpl-2.0.html\n";
        $css_content .= "Text Domain: " . $child_slug . "\n";
        $css_content .= "*/\n\n";
        $css_content .= "/* =Theme customization starts here\n";
        $css_content .= "------------------------------------------------------------ */\n";
        
        $style_css = trailingslashit($child_dir) . 'style.css';
        if (!file_put_contents($style_css, $css_content)) {
            // Clean up
            $this->delete_theme($child_slug);
            return new WP_Error('css_failed', __('Failed to create style.css.', 'wp-child-theme-pro'));
        }
        
        // Create functions.php
        $functions_content = "<?php\n";
        $functions_content .= "/**\n";
        $functions_content .= " * " . $child_name . " functions and definitions\n";
        $functions_content .= " * Generated by WP Child Theme Pro\n";
        $functions_content .= " * \n";
        $functions_content .= " * @package " . str_replace(' ', '_', $child_name) . "\n";
        $functions_content .= " */\n\n";
        $functions_content .= "/**\n";
        $functions_content .= " * Enqueue parent theme styles and child theme CSS\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_enqueue_styles() {\n";
        $functions_content .= "    wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');\n";
        $functions_content .= "    wp_enqueue_style('child-style',\n";
        $functions_content .= "        get_stylesheet_directory_uri() . '/style.css',\n";
        $functions_content .= "        array('parent-style'),\n";
        $functions_content .= "        wp_get_theme()->get('Version')\n";
        $functions_content .= "    );\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_enqueue_scripts', '" . str_replace('-', '_', $child_slug) . "_enqueue_styles');\n\n";
        
        // Add custom JS enqueue if needed
        $functions_content .= "/**\n";
        $functions_content .= " * Enqueue child theme scripts\n";
        $functions_content .= " */\n";
        $functions_content .= "function " . str_replace('-', '_', $child_slug) . "_enqueue_scripts() {\n";
        $functions_content .= "    // Enqueue custom JS if it exists\n";
        $functions_content .= "    if (file_exists(get_stylesheet_directory() . '/js/custom.js')) {\n";
        $functions_content .= "        wp_enqueue_script('child-custom-script',\n";
        $functions_content .= "            get_stylesheet_directory_uri() . '/js/custom.js',\n";
        $functions_content .= "            array('jquery'),\n";
        $functions_content .= "            wp_get_theme()->get('Version'),\n";
        $functions_content .= "            true\n";
        $functions_content .= "        );\n";
        $functions_content .= "    }\n";
        $functions_content .= "}\n";
        $functions_content .= "add_action('wp_enqueue_scripts', '" . str_replace('-', '_', $child_slug) . "_enqueue_scripts');\n\n";
        
        // Add more custom functionality
        $functions_content .= "// Add any custom functions below this line\n";
        
        $functions_php = trailingslashit($child_dir) . 'functions.php';
        if (!file_put_contents($functions_php, $functions_content)) {
            // Clean up
            $this->delete_theme($child_slug);
            return new WP_Error('functions_failed', __('Failed to create functions.php.', 'wp-child-theme-pro'));
        }
        
        // Create screenshot.png
        $this->create_screenshot($parent_theme, $child_dir);
        
        // Create JS directory and file
        $js_dir = trailingslashit($child_dir) . 'js';
        if (!wp_mkdir_p($js_dir)) {
            // Not fatal, continue
            error_log('Failed to create JS directory in child theme.');
        } else {
            // Create custom.js
            $js_content = "/**\n";
            $js_content .= " * Custom JS for " . $child_name . "\n";
            $js_content .= " * Generated by WP Child Theme Pro\n";
            $js_content .= " */\n\n";
            $js_content .= "jQuery(document).ready(function($) {\n";
            $js_content .= "    // Add your custom JavaScript code here\n";
            $js_content .= "    console.log('Child theme custom JS loaded');\n";
            $js_content .= "});\n";
            
            $custom_js = trailingslashit($js_dir) . 'custom.js';
            file_put_contents($custom_js, $js_content);
        }
        
        // Copy selected files from parent theme
        if (!empty($selected_files) && is_array($selected_files)) {
            $parent_dir = get_theme_root() . '/' . $parent_theme;
            foreach ($selected_files as $file) {
                $this->copy_parent_file($parent_dir, $child_dir, $file);
            }
        }
        
        // Copy parent theme settings if enabled
        if ($copy_settings) {
            $this->copy_parent_settings($parent_theme, $child_slug);
        }
        
        return $child_slug;
    }

    /**
     * Copy a file from parent theme to child theme
     *
     * @param string $parent_dir Parent theme directory
     * @param string $child_dir Child theme directory
     * @param string $file File path relative to theme root
     */
    private function copy_parent_file($parent_dir, $child_dir, $file) {
        $file = sanitize_file_name($file);
        $source = trailingslashit($parent_dir) . $file;
        $destination = trailingslashit($child_dir) . $file;
        
        // Skip if source doesn't exist
        if (!file_exists($source)) {
            return;
        }
        
        // Create directory if needed
        $destination_dir = dirname($destination);
        if (!is_dir($destination_dir)) {
            wp_mkdir_p($destination_dir);
        }
        
        // Copy file
        copy($source, $destination);
    }

    /**
     * Copy parent theme settings to child theme
     *
     * @param string $parent_theme Parent theme slug
     * @param string $child_theme Child theme slug
     */
    private function copy_parent_settings($parent_theme, $child_theme) {
        // Get all theme mods for parent theme
        $parent_mods = get_option('theme_mods_' . $parent_theme);
        
        if ($parent_mods) {
            // Set theme mods for child theme
            update_option('theme_mods_' . $child_theme, $parent_mods);
        }
    }

    /**
     * Create screenshot for child theme
     *
     * @param string $parent_theme Parent theme slug
     * @param string $child_dir Child theme directory
     */
    private function create_screenshot($parent_theme, $child_dir) {
        // Check if parent theme has screenshot
        $parent_screenshot = get_theme_root() . '/' . $parent_theme . '/screenshot.png';
        
        if (file_exists($parent_screenshot)) {
            // Copy parent screenshot
            copy($parent_screenshot, trailingslashit($child_dir) . 'screenshot.png');
        } else {
            // Create default screenshot
            $this->create_default_screenshot($child_dir);
        }
    }

    /**
     * Create default screenshot
     *
     * @param string $child_dir Child theme directory
     */
    private function create_default_screenshot($child_dir) {
        // Use GD to create a simple screenshot
        if (function_exists('imagecreatetruecolor')) {
            $image = imagecreatetruecolor(1200, 900);
            $bg_color = imagecolorallocate($image, 240, 240, 240);
            $text_color = imagecolorallocate($image, 51, 51, 51);
            
            imagefill($image, 0, 0, $bg_color);
            
            // Add text if GD with FreeType is available
            if (function_exists('imagettftext')) {
                $font = WPCHILD_PLUGIN_DIR . 'includes/assets/OpenSans-Regular.ttf';
                
                if (file_exists($font)) {
                    imagettftext($image, 40, 0, 100, 400, $text_color, $font, 'Child Theme');
                    imagettftext($image, 20, 0, 100, 450, $text_color, $font, 'Generated by WP Child Theme Pro');
                } else {
                    // Fallback to basic text
                    imagestring($image, 5, 100, 400, 'Child Theme', $text_color);
                    imagestring($image, 3, 100, 450, 'Generated by WP Child Theme Pro', $text_color);
                }
            } else {
                // Fallback to basic text
                imagestring($image, 5, 100, 400, 'Child Theme', $text_color);
                imagestring($image, 3, 100, 450, 'Generated by WP Child Theme Pro', $text_color);
            }
            
            // Save as PNG
            imagepng($image, trailingslashit($child_dir) . 'screenshot.png');
            imagedestroy($image);
        }
    }

    /**
     * Delete a theme
     *
     * @param string $theme_slug Theme slug
     */
    private function delete_theme($theme_slug) {
        $theme_dir = get_theme_root() . '/' . $theme_slug;
        $this->recursive_delete($theme_dir);
    }

    /**
     * Recursively delete a directory
     *
     * @param string $dir Directory path
     */
    private function recursive_delete($dir) {
        if (!is_dir($dir)) {
            return;
        }
        
        $files = array_diff(scandir($dir), array('.', '..'));
        
        foreach ($files as $file) {
            if (is_dir("$dir/$file")) {
                $this->recursive_delete("$dir/$file");
            } else {
                unlink("$dir/$file");
            }
        }
        
        rmdir($dir);
    }

    /**
     * Get list of files from parent theme
     *
     * @param string $parent_theme Parent theme slug
     * @return array File list
     */
    public function get_parent_theme_files($parent_theme) {
        $parent_dir = get_theme_root() . '/' . $parent_theme;
        
        if (!is_dir($parent_dir)) {
            return array();
        }
        
        return $this->scan_directory($parent_dir, '', array());
    }

    /**
     * Scan directory recursively
     *
     * @param string $base Base directory
     * @param string $dir Current directory
     * @param array $results Results array
     * @return array File list
     */
    private function scan_directory($base, $dir, $results) {
        $files = scandir($base . '/' . $dir);
        
        foreach ($files as $file) {
            if ($file == '.' || $file == '..') {
                continue;
            }
            
            $path = $dir . ($dir ? '/' : '') . $file;
            $full_path = $base . '/' . $path;
            
            if (is_dir($full_path)) {
                $results = $this->scan_directory($base, $path, $results);
            } else {
                $results[] = $path;
            }
        }
        
        return $results;
    }
}
